"use client";

import { useState } from "react";
import { CheckCircle2, Plus } from "lucide-react";
import type { AlertEvent, AlertRule, Dataset } from "@/types";

export function AlertManager({ initialAlerts, initialRules, datasets }: { initialAlerts: AlertEvent[]; initialRules: AlertRule[]; datasets: Dataset[] }) {
  const [alerts, setAlerts] = useState(initialAlerts); const [rules, setRules] = useState(initialRules); const [comment, setComment] = useState<Record<string, string>>({}); const [message, setMessage] = useState<string>();
  const dataset = datasets[0]; const numericFields = dataset?.fields.filter((field) => field.semanticType === "measure") ?? [];

  async function acknowledge(id: string) { const response = await fetch(`/api/alerts/${id}/acknowledge`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ comment: comment[id] || "Reviewed by operations." }) }); if (response.ok) { const payload = await response.json() as { alert: AlertEvent }; setAlerts((current) => current.map((item) => item.id === id ? payload.alert : item)); } }
  async function createRule(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); const response = await fetch("/api/alert-rules", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: form.get("name"), datasetId: dataset?.id, field: form.get("field"), operator: form.get("operator"), threshold: Number(form.get("threshold")), severity: form.get("severity") }) }); const payload = await response.json() as { rule?: AlertRule; error?: { message?: string } }; if (response.ok && payload.rule) { setRules((current) => [...current, payload.rule as AlertRule]); formElement.reset(); setMessage("Alert rule created."); } else setMessage(payload.error?.message ?? "Unable to create alert rule."); }

  return <>
    <section className="panel"><div className="panel-header"><div><h2>Alert events</h2><p>Open, acknowledged, and resolved operational signals.</p></div></div>{alerts.map((alert) => <div className="alert-row" key={alert.id}><span className={`alert-dot ${alert.severity}`} /><div><h3>{alert.ruleName} <span className={`badge ${alert.severity}`}>{alert.severity}</span></h3><p>{alert.message}</p><small>{new Date(alert.firedAt).toLocaleString()} · {alert.status}</small>{alert.status === "open" && <div className="table-actions" style={{ marginTop: 9 }}><input aria-label={`Acknowledgement for ${alert.ruleName}`} value={comment[alert.id] ?? ""} onChange={(event) => setComment((current) => ({ ...current, [alert.id]: event.target.value }))} placeholder="Acknowledgement comment" /><button className="button" onClick={() => acknowledge(alert.id)}><CheckCircle2 size={14} /> Acknowledge</button></div>}{alert.acknowledgement && <p className="status-banner" style={{ marginTop: 9 }}>Acknowledged by {alert.acknowledgement.userDisplayName}: {alert.acknowledgement.comment}</p>}</div><span className={`badge ${alert.status}`}>{alert.status}</span></div>)}</section>
    <section className="panel"><div className="panel-header"><div><h2>Structured alert rules</h2><p>Registered numeric field, fixed comparison, threshold, and severity only.</p></div></div><table className="admin-table"><thead><tr><th>Rule</th><th>Field</th><th>Condition</th><th>Severity</th><th>Status</th></tr></thead><tbody>{rules.map((rule) => <tr key={rule.id}><td>{rule.name}</td><td><code>{rule.field}</code></td><td>{rule.operator} {rule.threshold}</td><td><span className={`badge ${rule.severity}`}>{rule.severity}</span></td><td>{rule.enabled ? "Enabled" : "Disabled"}</td></tr>)}</tbody></table>
      <form className="form-grid" style={{ marginTop: 16 }} onSubmit={createRule}><label>Name<input name="name" required minLength={2} /></label><label>Field<select name="field">{numericFields.map((field) => <option value={field.key} key={field.id}>{field.displayName}</option>)}</select></label><label>Operator<select name="operator"><option value="lessThan">Less than</option><option value="lessThanOrEqual">Less than or equal</option><option value="greaterThan">Greater than</option><option value="greaterThanOrEqual">Greater than or equal</option><option value="equals">Equals</option></select></label><label>Threshold<input name="threshold" type="number" step="any" required /></label><label>Severity<select name="severity"><option value="info">Info</option><option value="warning">Warning</option><option value="critical">Critical</option></select></label><div style={{ alignSelf: "end" }}><button className="button primary" type="submit"><Plus size={14} /> Add rule</button></div></form>{message && <p className="status-banner" style={{ marginTop: 12 }}>{message}</p>}<p className="muted">Arbitrary SQL, JavaScript, and executable expression strings are rejected.</p>
    </section>
  </>;
}
